# Exercícios NumPy

In [ ]:
import numpy as np

# EX01

Inspecionando um Array NumPy

Um objeto numpy possui atributos e métodos, herdados da classe (numpy.ndarray). Crie um array  e inspecione os seguintes atributos:

shape: uma tupla que contém o número de elementos (tamanho) em cada dimensão do array;

size: número total de elementos do array;

ndim: número de dimensões (eixos);

nbytes: número de bytes utilizado no armazenamento dos dados;

dtype: data type dos elementos do array.

In [ ]:
array = np.array([1, 2, 3, 4, 5])
print(f'''
    Shape: {array.shape}
    Size: {array.size}
    Ndim: {array.ndim}
    Nbytes: {array.nbytes}
    Dtype: {array.dtype}

''')


    Shape: (5,)
    Size: 5
    Ndim: 1
    Nbytes: 40
    Dtype: int64




# EX02

Com base no exercício anterior crie uma função que receba um array e mostre na tela seus atributos. Verifique se o argumento inserido é de fato um objeto numpy. Use também a função built-in type() para verificar a classe do objeto.

In [ ]:
def inspecionar_array(array):
    if isinstance(array, np.ndarray):
        print('Shape: ', array.shape)
        print('Size: ', array.size)
        print('Ndim: ', array.ndim)
        print('Nbytes: ', array.nbytes)
        print('Dtype: ', array.dtype)
        print('Type: ', type(array))
    else:
        return 'O objeto inserido não é um array NumPy.'

array = np.array([1, 2, 3, 4])
lista = [1, 2, 3, 4]

inspecionar_array(array)
inspecionar_array(lista)

Shape:  (4,)
Size:  4
Ndim:  1
Nbytes:  32
Dtype:  int64
Type:  <class 'numpy.ndarray'>


'O objeto inserido não é um array NumPy.'

# EX03

Use a função np.array() para criar os arrays unidimensionais listados abaixo:

a) Use uma lista como argumento e obtenha:



array([-1,  4,  7,  9])


b) Use a função range() e obtenha:



    
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


c)Use uma tupla como argumento e obtenha:



    
array([10, 11, 12, 13, 14])


d) Use a função range() e obtenha:



    
array([1990, 1995, 2000, 2005, 2010, 2015, 2020])


e) Use a função range() e obtenha:



array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,
       1910, 1900])


f) Obtenha:



array(100)

In [ ]:
np.array([-1, 4, 7, 9])

array([-1,  4,  7,  9])

In [ ]:
np.array(range(1, 11))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.array((10, 11, 12, 13, 14))

array([10, 11, 12, 13, 14])

In [ ]:
np.array(range(1990, 2021, 5))

array([1990, 1995, 2000, 2005, 2010, 2015, 2020])

In [ ]:
np.array(range(2020, 1890, -10))

array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,
       1910, 1900])

In [ ]:
np.array(100)

array(100)

# EX04

A função np.ones() permite criar um array preenchido com o número 1 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array. Use esta função para criar os arrays a seguir:

a)



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


b)



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
       

c)



array([[1, 1],
       [1, 1],
       [1, 1]])


In [ ]:
np.ones(10, dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(shape=(4, 4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(3, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

# EX05

A função np.zeros() permite criar um array preenchido com o número 0 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array (default é o float). Use esta função para criar os arrays a seguir:

a)



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


b)



array([[0., 0.],
       [0., 0.]])  
       

c)



array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(shape=(2, 2), dtype=float)

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros(shape=(4, 6), dtype=float)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# EX06

Crie os arrays a seguir:

   

a)



array([[10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45]])


b)



array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])


c)



array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])
       

Dica: use np.arange() ou np.array(range()).

In [ ]:
np.array([10, 15, 20, 25, 30, 35, 40, 45]).reshape(-1, 1)

array([[10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45]])

In [ ]:
np.arange(-50, 0, 5)

array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])

In [ ]:
np.arange(50, 150, 2).reshape((5, 10))

array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])

# EX07

Utilize a função np.full(shape, fill_value, dtype) para criar os arrays a seguir. Esta função permite criar um array com um shape e dtype definidos pelo usuário, preenchido com um determinado valor.

a)



`array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])`


b)



`array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])`




c)



`array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])`

d)



`array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])`


Dica: outra possibilidade seria obter os arrays com uma operação diferente, a partir da multiplicação de uma matriz preenchida com número 1 por um determinado valor.

In [ ]:
np.full(10, 5, dtype=float)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.full(shape=(4, 4), fill_value=-5, dtype=float)

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [ ]:
np.full(shape=(3, 3), fill_value=3, dtype=int)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
np.full(shape=(10, 10), fill_value=50, dtype=int)

array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

# EX08

Defina o array K e verifique se há dados ausentes (missing data). Use a função np.isnan().

```
array([[ nan,   1.,  10.,   0.],
       [ nan,  nan,  nan,  nan],
       [100.,  50.,  nan, -25.],
       [ 30.,  nan,  nan, 130.]])
```



In [ ]:
array = np.array([[np.nan, 1., 10., 0], [np.nan, np.nan, np.nan, np.nan], [np.nan, 50., np.nan, -25.], [30., np.nan, np.nan, 130.]])
array

array([[ nan,   1.,  10.,   0.],
       [ nan,  nan,  nan,  nan],
       [ nan,  50.,  nan, -25.],
       [ 30.,  nan,  nan, 130.]])

In [ ]:
np.isnan(array)
np.isnan(array).sum()

9

# EX09

A função np.linspace() retorna um array com números contendo espaçamento uniforme em um intervalo definido. Crie um array com números dentro do intervalo [1,21] em 5 partes.

Retorno esperado:



array([ 1.,  6., 11., 16., 21.])

In [ ]:
np.linspace(1, 21, 5)

array([ 1.,  6., 11., 16., 21.])

#EX10

A função np.logspace() retorna números com espaçamento uniforme em uma escala logarítmica. Crie um array com números dentro do intervalo [1, 51] em 10 partes com a função np.logspace().

Retorno esperado:

```
array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])
```





In [ ]:
np.logspace(1, 51, 10).reshape(-1, 1)

array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])

#EX11

Use a função np.diag() para construir o array a seguir:

```
array([[ 5,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  0, 25,  0],
       [ 0,  0,  0,  0,  0, 30]])
```



In [ ]:
x = np.array([5, 10, 15, 20, 25, 30])
np.diag(x)

# ou 

np.diag(np.arange(5, 31, 5))

array([[ 5,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  0, 25,  0],
       [ 0,  0,  0,  0,  0, 30]])

#EX12

Use a função np.eye() (ou ainda np.identity()) para obter o array seguir.



```array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])```



In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#EX13

Obtenha a soma dos elementos de cada array a seguir. Use a função np.sum(). Implemente uma solução com loop for, para tanto armazene os vetores em uma lista.




```
import numpy as np
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))
```

Retorno esperado:

```
Soma dos elementos do array 1:  55
Soma dos elementos do array 2:  255.0
Soma dos elementos do array 3:  1275
Soma dos elementos do array 4:  10056552148.564463
Soma dos elementos do array 5:  105
```

In [ ]:
import numpy as np
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))

In [ ]:
# solucao 1
print(f'''
    Soma dos elementos do array 1: {array1.sum()}
    Soma dos elementos do array 2: {array2.sum()}
    Soma dos elementos do array 3: {array3.sum()}
    Soma dos elementos do array 4: {array4.sum()}
    Soma dos elementos do array 5: {array5.sum()}
''')


    Soma dos elementos do array 1: 55
    Soma dos elementos do array 2: 255.0
    Soma dos elementos do array 3: 1275
    Soma dos elementos do array 4: 10056552148.564463
    Soma dos elementos do array 5: 105





In [ ]:
# solucao 2
arrays = [array1, array2, array3, array4, array5]

for index, array in enumerate(arrays, start=1):
    print(f'A soma do {index}º array é {array.sum()}')

A soma do 1º array é 55
A soma do 2º array é 255.0
A soma do 3º array é 1275
A soma do 4º array é 10056552148.564463
A soma do 5º array é 105


# EX14

A partir da matriz definida abaixo obtenha:

a) soma total dos elementos; 

b) soma das linhas;

c) soma das colunas.


```
import numpy as np
matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)
```






In [ ]:
matriz = np.array(np.random.randint(1,100,15)).reshape(5,3)
matriz

array([[48, 56, 11],
       [ 9, 69, 86],
       [38, 41, 46],
       [23, 13, 18],
       [97, 98, 89]])

In [ ]:
matriz.sum()

742

In [ ]:
# linhas
matriz.sum(axis=0)

array([215, 277, 250])

In [ ]:
# colunas
matriz.sum(axis=1)

array([115, 164, 125,  54, 284])

# EX15

Obtenha o valor máximo e o valor mínimo de cada array abaixo. Implemente uma solução com loop for.


```
import numpy as np
array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))
```



Dica: para obter o valor máximo e mínimo de um array podemos usar array.max() e array.min() ( ou ainda max(array) e min(array)).


In [ ]:
array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))
arrays = [array1, array2, array3, array4]

In [ ]:
for indice, array in enumerate(arrays, start=1):
    print(f'Soma do {indice}º: {array.sum()}')

Soma do 1º: 50
Soma do 2º: 3086
Soma do 3º: 2.707741976964769
Soma do 4º: 620


#EX16

Crie uma função que receba uma matriz como entrada e calcule:

    a) Valor máximo da matriz;

    b) Valor máximo por coluna;

    c) Valor máximo por linha;

    d) Valor mínimo da matriz;

    e) Valor mínimo por coluna;

    f) Valor mínimo por linha.





In [ ]:
def calcula_matriz(matriz):
    if isinstance(matriz,np.ndarray) and matriz.ndim == 2:
        print(f'Valor máximo da matriz: {matriz.max()}')
        print(f'Valor máximo por coluna: {matriz.max(axis=0)}')
        print(f'Valor máximo por linha: {matriz.max(axis=1)}')
        print(f'Valor mínimo da matriz: {matriz.min()}')
        print(f'Valor mínimo por coluna: {matriz.min(axis=0)}')
        print(f'Valor mínimo por linha: {matriz.min(axis=1)}')
    else:
        return None


matriz = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [3, 46, 22, 34, 22]])
calcula_matriz(matriz)

Valor máximo da matriz: 46
Valor máximo por coluna: [ 6 46 22 34 22]
Valor máximo por linha: [ 5 10 46]
Valor mínimo da matriz: 1
Valor mínimo por coluna: [1 2 3 4 5]
Valor mínimo por linha: [1 6 3]


# EX17

Com base no array definido abaixo obtenha sua média, mediana, variância e desvio padrão.




`arr = np.random.normal(40,0.5,size = (300))`

In [ ]:
array = np.random.normal(40,0.5,size = (300))
array

array([40.15131592, 40.96900222, 39.94696253, 38.88698449, 39.60532502,
       39.23182209, 40.22514259, 40.13268083, 39.69961417, 39.94776538,
       39.9739828 , 40.34359331, 40.24961198, 40.72380031, 40.53569537,
       39.95734874, 40.09004747, 40.34240816, 40.3973736 , 40.86654411,
       39.53191397, 39.84238761, 39.58929095, 40.11099295, 39.72539303,
       40.19585562, 39.60090313, 40.20149658, 39.58562276, 39.2873431 ,
       39.8438225 , 40.30776891, 40.37494683, 40.18656398, 39.16517637,
       39.83517041, 40.1650073 , 39.80449317, 39.39927423, 40.48809443,
       40.46621934, 39.88161324, 40.07683696, 40.08260863, 40.31951283,
       39.85566559, 39.89110103, 40.28663571, 39.94502918, 40.56602251,
       40.13960316, 40.60226676, 39.62277297, 40.00094802, 40.11562329,
       39.33614063, 39.32782008, 40.01401271, 39.79578626, 40.78641989,
       40.50696803, 39.84379716, 40.85632508, 40.46787651, 40.0114316 ,
       40.10966184, 39.3584753 , 40.3197284 , 40.19014515, 39.75

In [ ]:
array.mean()

40.02575620276213

In [ ]:
np.median(array)

40.019947945490664

In [ ]:
np.std(array)

0.4908753640177812

In [ ]:
np.var(array)

0.24095862299958923

# EX18

Com base nos arrays definidos a seguir obtenha a matriz de covariância e a matriz de correlação.



`x = np.random.rand(100)`

`y = np.random.uniform(size=100)`

In [ ]:
x = np.random.rand(100)
y = np.random.uniform(size=100)


In [ ]:
np.corrcoef(x, y)

array([[1.        , 0.03647407],
       [0.03647407, 1.        ]])

In [ ]:
np.cov(x, y)

array([[0.09192672, 0.00325326],
       [0.00325326, 0.0865423 ]])

# EX19

Obtenha o índice do valor máximo do array A.



```
A = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])
```



In [ ]:
A = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])

A.argmax()

9

# EX20

Obtenha o índice do valor mínimo do array B.



```
B = np.array([
    [73, 22, 20, 62,  3],
    [68, 84, 27, 59, 93],
    [48, 52,  4, 55, 50],
    [42, 23, 63, 67,  4],
    [44, 30, 41, 31, 29]])
```



In [ ]:
B = np.array([
    [73, 22, 20, 62,  3],
    [68, 84, 27, 59, 93],
    [48, 52,  4, 55, 50],
    [42, 23, 63, 67,  4],
    [44, 30, 41, 31, 29]])

B.argmin()

4

# EX21

Escreva uma função que receba um array NumPy e mostre na tela um conjunto de  estatísticas descritivas deste objeto.

In [ ]:
array = np.array([-57, 101, 270, 130, 144])

def info_array(array):
    if isinstance(array, np.ndarray):
        print(f'Valor máximo: {array.max()}')
        print(f'Valor mínimo: {array.min()}')
        print(f'Média: {array.mean()}')
        print(f'Mediana: {np.median(array)}')
        print(f'Variância: {array.var()}')
        print(f'Desvio padrão: {array.std()}')


info_array(array)

Valor máximo: 270
Valor mínimo: -57
Média: 117.6
Mediana: 130.0
Variância: 10967.439999999999
Desvio padrão: 104.72554607162475


# EX22

Use a função np.unique() para obter um array com os elementos únicos do array abaixo. Para tanto, armazene o novo array em uma variável.



```
A = np.array([
    [1, 3, 3, 4, 5],
    [4, 7, 11, 3, 5],
    [1, 11, 4, 4, 11]])
```



In [ ]:
A = np.array([
    [1, 3, 3, 4, 5],
    [4, 7, 11, 3, 5],
    [1, 11, 4, 4, 11]])

novo_array = np.unique(A)
novo_array

array([ 1,  3,  4,  5,  7, 11])

# EX23

Considerando os arrays abaixo:



```
array1 = np.array([10, 20, 30, 40])
array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])
```

Obtenha:

a) o primeiro, o terceiro e o último elemento de cada array;

b) inverta o array;

c) pegue o número 20 em ambos os arrays e armazene a soma em uma variável.

In [ ]:
array1 = np.array([10, 20, 30, 40])
array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])
arrays = [array1, array2]

In [ ]:
for index, array in enumerate(arrays, start=1):
    print(f'Array: {index}')
    print(f'Primeiro elemento: {array[0]}')
    print(f'Terceiro elemento: {array[2]}')
    print(f'Último elemento: {array[-1]}')
    print(f'Array invertido: {array[::-1]}')

soma = array1[1] + array2[6]
print(soma)

Array: 1
Primeiro elemento: 10
Terceiro elemento: 30
Último elemento: 40
Array invertido: [40 30 20 10]
Array: 2
Primeiro elemento: 100
Terceiro elemento: 5
Último elemento: 170
Array invertido: [170 155 130  20 100  40   1   5  30 100]
40


# EX24

Acesse os números 9 e 90 do array abaixo.


`ar = np.array([[-1, 33, 44, 9, 1],[11, 1, 0, 90, 44]])`

In [ ]:
ar = np.array([[-1, 33, 44, 9, 1],[11, 1, 0, 90, 44]])
ar

array([[-1, 33, 44,  9,  1],
       [11,  1,  0, 90, 44]])

In [ ]:
ar[0, 3]

9

In [ ]:
ar[1, 3]

90

# EX25

Acesse os números 5, 9, 3 e 21 do array abaixo.



```
ar = np.array([
    [[1, 1, 5, 1],
     [1, 1, 1, 9]],
    [[1, 3, 1, 1],
     [1, 1, 21, 1]]
              ])
```



In [ ]:
ar = np.array([
    [[1, 1, 5, 1],
     [1, 1, 1, 9]],
    [[1, 3, 1, 1],
     [1, 1, 21, 1]]
              ])

ar

array([[[ 1,  1,  5,  1],
        [ 1,  1,  1,  9]],

       [[ 1,  3,  1,  1],
        [ 1,  1, 21,  1]]])

In [ ]:
ar[0, 0, 2]

5

In [ ]:
ar[0, 1, -1]

9

In [ ]:
ar[1, 0, 1]

3

In [ ]:
ar[1, 1, 2]

21

# EX26

Com base no array abaixo obtenha o slice do índice 2 até o índice 6.

`ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])`

Dica: Em Python, slicing significa que podemos selecionar elementos entre índices especificados. Sintaxe: [start:end:pass].

Se não especificarmos o start o valor default será 0. Se não definirmos o step, será considerado o valor 1.



In [ ]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ar[2:7]

array([3, 4, 5, 6, 7])