In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [ ]:
array2 = np.arange(10)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array3 = np.loadtxt('carros-km.txt', dtype=int)
array3

In [ ]:
array4 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
array4

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
dados = [1, 2, 3, 4, 5]
dados2 = [1, 2, 3, 4, 5]
array5 = np.array([dados, dados2])
array5

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
km = np.array([44410., 5712., 37123., 0., 25757.,])
anos = np.array([2003, 1991, 1990, 2019, 2006])
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
km_media = dados[0] / (2019 - dados[1])
km_media

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [ ]:
dados[0, 1]

5712.0

In [ ]:
dados[0, 0:4]

array([44410.,  5712., 37123.,     0.])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[:, 0:3]

array([[44410.,  5712., 37123.],
       [ 2003.,  1991.,  1990.]])

In [ ]:
km_media = dados[:, 0:3][0] / (2019 - dados[:, 0:3][1])
km_media

array([2775.625     ,  204.        , 1280.10344828])

In [ ]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array[array > 5]

array([6, 7, 8, 9])

In [ ]:
acima_de_2000 = dados[:, dados[1] > 2000]
acima_de_2000

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [ ]:
dados = np.array([[44410., 5712., 37123., 0., 25757.],
                  [2003, 1991, 1990, 2019, 2006]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados.shape

(2, 5)

In [ ]:
dados.ndim

2

In [ ]:
dados.size

10

In [ ]:
dados.dtype

dtype('float64')

In [ ]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [ ]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [ ]:
dados.reshape((5, 2), order='C')

array([[44410.,  5712.],
       [37123.,     0.],
       [25757.,  2003.],
       [ 1991.,  1990.],
       [ 2019.,  2006.]])

In [ ]:
dados


array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados.resize((5, 5), refcheck=False)

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     0.,     0.]])